/** Standard foreign LLC registration reference, checked 2026-09-23.
 * Base filing only; not an all-in authorization price. See notes and source.
 * Not for domestic formation, corporations, series LLCs or licensed professions.
 */
export interface FilingReference { amount: number; url: string; note: string }
const fees: [string, number, string, string?][] = [
  ["AL",150,"https://www.sos.alabama.gov/business-entities/llcs","Name reservation is also required and priced separately."],
  ["AK",350,"https://www.commerce.alaska.gov/web/cbpl/Corporations/CorporationFormsFees","Foreign LLC biennial report: $200; business licensing is separate."],
  ["AZ",150,"https://www.azcc.gov/docs/default-source/corps-files/fee-schedules/fee-schedule-llcs646a1cd0d6b24246ab2253aecbc3ab40.pdf","Regular processing; publication and expedited service, if applicable, are additional."],
  ["AR",270,"https://www.sos.arkansas.gov/business-commercial-services-bcs/forms-fees/llc/foreign-llc","Online $270; paper $300. Annual franchise-tax obligations are separate."],
  ["CA",70,"https://bpd.cdn.sos.ca.gov/llc/forms/llc-5.pdf","Statement of Information and potential $800 annual minimum tax are additional."],
  ["CO",100,"https://www.sos.state.co.us/pubs/info_center/fees/business.html","Foreign Entity Authority Statement; periodic report $25."],
  ["CT",120,"https://portal.ct.gov/-/media/SOTS/Business-Services/BSD-Forms/Limited-Liability-Partnership/Foreign/Foreign_Registration_Statement_LLC_Foreign_FILLABLE_20220125.pdf"],
  ["DE",200,"https://delcode.delaware.gov/title6/c018/sc11/","Section 18-1105(a)(6); annual entity tax is additional."],
  ["FL",125,"https://dos.fl.gov/sunbiz/forms/fees/","Includes $100 filing + $25 agent designation; annual report $138.75. Optional copies excluded."],
  ["GA",235,"https://sos.ga.gov/index.php/node/1925","$225 filing plus $10 service charge; annual registration is separate."],
  ["HI",51,"https://cca.hawaii.gov/breg/registration/fllc/","$50 filing plus $1 State Archives charge; expedited service excluded."],
  ["ID",100,"https://sos.idaho.gov/CORP/forms/FOREIGN/foreign%20reg%20statement.pdf","Online base fee; paper adds $20 manual processing."],
  ["IL",150,"https://www.ilsos.gov/publications/business-services/llc.html","Standard LLC; series LLC fee differs."],
  ["IN",125,"https://forms.in.gov/Download.aspx?id=13562","Paper for-profit registration; electronic fees can differ; master series LLC excluded."],
  ["IA",100,"https://sos.iowa.gov/businesses/business-entity-forms-and-fees"],
  ["KS",115,"https://www.sos.ks.gov/forms/business_services/FA.pdf","March 2026 Form FA total; older fee schedules may differ."],
  ["KY",90,"https://www.sos.ky.gov/bus/business-filings/Pages/Fees.aspx","Annual report $15, separately payable."],
  ["LA",150,"https://www.sos.la.gov/business-services/forms-fee-schedule","$150 through September 30, 2026. Act 921 increases this to $185 October 1; recheck before filing."],
  ["ME",250,"https://www1.maine.gov/sos/corporations-commissions/i-need-a-business-form/limited-liability-company-forms","MLLC-12; foreign LLC annual report $150."],
  ["MD",100,"https://dat.maryland.gov/Documents/Accessible%20Documents/Charter%20-%20Foreign%20Businesses/Foreign%20Limited%20Liability%20Company%20Registration%20_%20Re-registration_0326-A.pdf"],
  ["MA",500,"https://www.sec.state.ma.us/divisions/corporations/filing-by-subject/limited-liability/corporations-foreign-limited-liability-company.htm","Annual reporting is required; processing extras are excluded."],
  ["MI",50,"https://www.michigan.gov/lara/-/media/Project/Websites/lara/cscl/NonImages_new/Corps/forms/llc/760-0625-f.pdf","CSCL/CD-760; expedited service excluded."],
  ["MN",185,"https://sos.mn.gov/fees","Mail $185; online/in person $205."],
  ["MS",250,"https://www.sos.ms.gov/content/documents/Business/FeeSchedule.pdf"],
  ["MO",105,"https://www.sos.mo.gov/CMSImages/Business/llc4.pdf"],
  ["MT",70,"https://sos.mt.gov/Portals/142/Business/Business_Filing_Fees.pdf","Standard foreign LLC; series members cost extra."],
  ["NE",110,"https://sos.nebraska.gov/business-services/forms-and-fee-information","Online $100 + $10 certificate; in-office $110 + $10 certificate."],
  ["NV",75,"https://www.leg.state.nv.us/NRS/NRS-086.html#NRS086Sec561","Registration only. Initial/annual list and state business license are additional; this is not the total startup cost."],
  ["NH",100,"https://www.sos.nh.gov/corporations-0/forms-and-fees/limited-liability-companies","Electronic submissions add $2 handling."],
  ["NJ",100,"https://nj.gov/treasury/revenue/fees.shtml","Published Treasury foreign-LLC registration fee; annual report $75; check portal total."],
  ["NM",100,"https://klvg4oyd4j.execute-api.us-west-2.amazonaws.com/prod/PublicFiles/ee3072ab0d43456cb15a51f7d82c77a2/1c940b98-cdb8-45ad-839f-7645c176a0c7/ch53Art19.pdf","NMSA 53-19-63 statutory reference; confirm current portal charges."],
  ["NY",250,"https://dos.ny.gov/application-authority-foreign-limited-liability-companies","Two designated newspapers, weekly for six weeks, within 120 days. Publication and certificate costs are additional."],
  ["NC",250,"https://www.sosnc.gov/manual/register_a_foreign_business/requirements"],
  ["ND",135,"https://www.sos.nd.gov/business/business-services/business-structures/limited-liability-company-llc","Annual report $50, separately payable."],
  ["OH",99,"https://www.ohiosos.gov/globalassets/publications/busserv/llc.pdf"],
  ["OK",300,"https://www.sos.ok.gov/business/forms.aspx","Annual certificate and agent costs are separate."],
  ["OR",275,"https://sos.oregon.gov/business/Documents/business-registry-forms/br-fee-schedule.pdf","Foreign registration; recurring renewal is separate."],
  ["PA",250,"https://www.pa.gov/content/dam/copapwp-pagov/en/dos/programs/business/forms/offsite-forms/15-412-Foreign-Registration-Statement.pdf","Annual reporting and professional-entity fees may apply separately."],
  ["RI",150,"https://www.sos.ri.gov/divisions/business-services/foreign-business/register-your-business-in-ri"],
  ["SC",110,"https://businessfilings.sc.gov/BusinessFiling/Home/DownloadForms?pdfCategoryId=1","LLC application under section 33-44-1002; do not use the corporation fee."],
  ["SD",750,"https://sdsos.gov/Division%20of%20Business%20Services/Filing%20Fees/default.aspx","Online $750; paper $765. Annual online report $55."],
  ["TN",300,"https://sos.tn.gov/businesses/forms-and-fees","Minimum fee only; $50 per member, minimum $300 and maximum $3,000. Membership is not employee headcount."],
  ["TX",750,"https://www.sos.texas.gov/corp/instructions/304.shtml","Late registration fees and business-tax obligations are additional."],
  ["UT",59,"https://corporations.utah.gov/wp-content/uploads/2023/04/currentfees.pdf","FY2026 published schedule; confirm current fees at filing."],
  ["VT",155,"https://legislature.vermont.gov/statutes/section/11/025/04012","Statutory certificate-of-authority fee; foreign annual report $170."],
  ["VA",100,"https://www.scc.virginia.gov/businesses/forms-and-fees/foreign-limited-liability-companies/"],
  ["WA",180,"https://www.sos.wa.gov/vi/node/11802","Base registration; expedited/online processing, business license and endorsements may add fees."],
  ["WV",150,"https://sos.wv.gov/business/registration-and-waivers/register-out-state-foreign-business","Separate business registration/tax requirements; veteran waivers may apply."],
  ["WI",100,"https://apps.dfi.wi.gov/apps/gofr/Form/Index/51","Late-registration penalties are additional."],
  ["WY",150,"https://sos.wyo.gov/forms/business/fllc/fllc-certificateauthority.pdf","Annual license tax and registered agent costs are additional."],
];
export const FILING_FEES: Record<string, FilingReference> = Object.fromEntries(fees.map(([code, amount, url, note]) => [code, { amount, url, note: note ?? "Standard application fee only; agent service, certificates, annual filings, licenses, taxes and expedited charges are additional where applicable." }]));
